{% set version = "0.7" %}

package:
  name: django-libsass
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-libsass/django-libsass-{{ version }}.tar.gz
  sha256: 49db3334b87e1f7955c4f9fb9945bc296f8bfd27a14d6d89706e4b0e5dc5de1c

build:
  number: 1
  skip: true  # [win and py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.8
    - django_compressor >=1.3
    - libsass >=0.7.0

about:
  home: https://github.com/torchbox/django-libsass
  license: BSD-3-Clause
  license_family: BSD
  # file not packaged; see https://github.com/torchbox/django-libsass/pull/28
  license_file: LICENSE
  summary: 'A django-compressor filter to compile SASS files using libsass'
  description: |
    A django-compressor filter to compile Sass files using libsass.
  doc_url: https://github.com/torchbox/django-libsass
  dev_url: https://github.com/torchbox/django-libsass

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
