{% set version = "0.9" %}

package:
  name: django-libsass
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-libsass/django-libsass-{{ version }}.tar.gz
  sha256: bfbbb55a8950bb40fa04dd416605f92da34ad1f303b10a41abc3232386ec27b5

build:
  number: 0
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.8
    - django_compressor >=1.3
    - libsass >=0.7.0

about:
  home: https://github.com/torchbox/django-libsass
  license: BSD-3-Clause
  license_family: BSD
  # file not packaged; see https://github.com/torchbox/django-libsass/pull/28
  license_file: LICENSE
  summary: A django-compressor filter to compile SASS files using libsass
  description: |
    A django-compressor filter to compile Sass files using libsass.
  doc_url: https://github.com/torchbox/django-libsass
  dev_url: https://github.com/torchbox/django-libsass

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - sannykr
