travis:
  secure:
    BINSTAR_TOKEN: pFfTDIayGxdqot7Jfn0f8oWio+/zEmvkC4nmt2Pn9p0MEWIaBOzWsBwBOvGfPEs+6BFruH2XbUlWBzqGisUYv21fLUaS2kHGa2clSwNE/k2P0+ex2NBR7qHvUQwEzgiH+mGQkttEBg1JQ1kDihtLFDUnemYfdssC62k+H+hjc5+nso8gYcqdB/H5gMVKh997+sOZihS2nfwW3sOex/yI413x+gtW+MUdahXYrbCrNPlCgUPIfAmaJaOt+CEWMBChvbQn/EXX2w8qpTrNqdmM6Bfo9E9rzPmg8rJap51Moa0R58QbnqUxh60vmgWzI35dtbJH79i+RyXe7agSkwOfaVodRb6qLj67lavCZWrvC7uy6P+oCYRboqUJoHrvBP2Lw0pZgvtC2g0bJ3w6IKZDWAfB+uYZ5slE8l2Iaw1q9iNMPNkkT+4stCgr4tbR1r3KHju6+i9eR0khngbQFH7gCac3MrK0UvPkP4H9+sQTwygxS1jdnP/rBMFGk2Sdz3uGZHDoziD9f4wS/m7lgjCU1jkugNfE2nVHX1PfaQjAx9D3J26rk6oemduYRkaZCYmIQo3Jd9hDoYOPwgET1jAGJ+bWbLoef0X3Jw+ZrqmpO62ZJhZLDykQefOjcalS4zpw+6gOiekpQ+OVEINZL9lvbOhxd5HK6R4HcaPW8Y2OoyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
