travis:
  secure:
    BINSTAR_TOKEN: mK6/aVRnjT5AW7cUHcWqS8FlBHd5i81nPnE1NH3tyZy6fZViJpo4Pclz47Zfsgjj0YdKCsrDyyBfg7OAUzr2ztiYfIAGVUyJiu3MuXPK4UrWA6Z1aw6vAieb20LkJzuUHS6qdq7iFT039BIWGvFI31MctfYMW+zHrvrFJoRYrQq0KVFffontjt0R+RgBk8fu193YVhGG8BJfv6F+B4eZPgfQGmQ3a4gwhxlq+2THhBjHwvIKORJnK5GOQgCj/LO5IIWq1r5zwT/r6pTqy7q5hxK37fpb9c2Y+LxD8+ygVRa6Vd1VKlbD/LwQDaYui9L5MExIWv01Unt5h91pzO9kdcvi03eCSdUaqWl0MXETuaJw/1CRiM02rNymMxgQin3+ckuOsfCWAtoJX6FfDWie7ugSpdACL1xRY8niUmMJTAoWyrDqRq87CnstRVGCEYLAhpRXOW0V6jNzgUgx4PLr0x3dCjTb9XQmv0yr2VglEWTNSsDWOjrIDo4vHK2HvdBEQSqtaVrpkjLRxDRH3quFl7oLGhO1Xwgc+tz9N3OPM/M+XE+3EVgoeiMKbkIJ7X6sh/ilXVmDgs2nMBc3A+tHKgJkx6/Mdd609+jaS3oGK0J49sbKhyw+Znv9828bp2yQ/H1z3yMWXryLCdCcFIOYx1xLOJegJGUZNCrD4uotwDg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
